### ISSUE TITLE
Crashed overnight with "The RPC server is unavailable"

### ISSUE THREAD

**Issue by pmcevoy** [efontana/TimberWinR#1]
TimberWinR 1.2.347, installed via Chocolatey

One of our chaps was running Timber overnight as a windows service and it crashed around midnight with the following error repeating every few seconds:

```
2015-01-26 09:33:36.7654|ERROR|TimberWinR.Inputs.LogsListener|System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
    at Interop.MSUtil.LogQueryClassClass.Execute(String szQuery, Object pObjectInputContext)
    at TimberWinR.Inputs.LogsListener.FileWatcher(String fileToWatch)
```

The service seems to have got into quite a state because we could not restart it through service manager, and we needed to manually kill it using procexp:

```
2015-01-26 09:33:36.7804|INFO|TimberWinR.Diagnostics.Diagnostics|Shutting down diagnostics listener
2015-01-26 09:33:36.7964|INFO|TimberWinR.Manager|Shutting Down
2015-01-26 09:33:36.8124|INFO|TimberWinR.Inputs.LogsListener|Shutting Down Win32-FileLog
2015-01-26 09:33:36.8124|INFO|TimberWinR.Inputs.InputListener|Shutting Down Win32-FileLog
2015-01-26 09:33:36.8604|INFO|TimberWinR.Inputs.InputListener|Signaling Event Shutdown Win32-FileLog
2015-01-26 09:33:36.8604|INFO|TimberWinR.Inputs.InputListener|Finished Wait For Win32-FileLog
2015-01-26 09:33:36.8604|INFO|TimberWinR.Inputs.InputListener|Finished signaling Shutdown Win32-FileLog
2015-01-26 09:33:36.8604|INFO|TimberWinR.Inputs.LogsListener|Shutting Down Win32-FileLog
2015-01-26 09:33:36.8754|INFO|TimberWinR.Inputs.InputListener|Shutting Down Win32-FileLog
2015-01-26 09:41:30.7424|INFO|TimberWinR.Manager|TimberWinR Version 1.2.347.0
2015-01-26 09:41:31.0034|INFO|TimberWinR.Manager|Database Directory: C:\Logs\.timberwinrdb
2015-01-26 09:41:31.0034|INFO|TimberWinR.Manager|Initialized, Reading Configurations From C:\Program Files (x86)\TimberWinR\Conf
```

**Comment by efontana** [comment]
Hmm. I've been running it continuously for over a month now, and haven't run into this.

This sounds related:

http://support.microsoft.com/kb/935677/en-us

**Comment by pmcevoy** [comment]
Sorry for going dark on this for a few days - I've been juggling a lot...

That KB relates to XP - we are using Windows 7 (.Net 4.5).

At the moment, we are trialing TimberWinr (shipper) -> Redis (buffer) -> LogStash (indexer) -> ElasticSearch on our local dev boxes - with a view to rolling out to our production (where load will be a lot heavier).

We need Timber to monitor _alot_ of log files - circa 20-30.  And some of those log files are very active.  The logfiles are written by log4net, and we have set it to roll at 5Mb.  During a system test run of our applications, the log files may rotate 3-4 times in a 40 min window.

Yesterday we saw another issue (which I think is related) where we saw the svchost that was hosting the DCOM serivce (dllhost.exe) had grown to 1.5Gb in working memory.  Stopping the TimberWinR service caused that process (dllhost.exe) to be release and the memory reclaimed.

My thoughts are that the LogParser library that TimberWinR is using has unmanaged code in it and _that_ is using some kind of COM stuff - but that's all wizadry to me.  My collegue thinks the issue may be related to the other issue I logged about configuring TimberWinR to monitor files that don't exist yet.  

We've taken a look at the code in LogListener.FileWatcher() and TBH are a little scared at the GC.Collect calls - that feels like you may have seen memory problems in the past?  again when it comes to memory management, it's all wizardry to me and I know enough to know that I don't know enough...

I'm happy to try and get you more information - but the team is pushing for us to use a native log4net redis appender and skip the shipper altogether:  But I believe there is value in shipping event logs and IIS logs, and would like to get TimberWinR robust.

Can you suggest a way forward?

**Comment by efontana** [comment]
Hello There.

The GC.Collects were added because I had seen problems in the past with
excessive memory consumption, and as you implied I think the unmanaged
code needed a kick to release it's memory.  The LogParser seems to be not
the most efficient for tailing of large files, TimberWinR doesn't store any
memory other than a simple hash table of logfileName to last Index parsed
for tailing purposes.     I do agree with you that shipping directly to
redis
is not the best approach because you don't have any filtering or mutating
in that fashion.

Interestingly enough, we here (at Vistaprint) have TimberWinR in production
and we stopped using Logfiles altogether, and everyone is using a Tcp
or Udp appender which TimberWinR eats up nicely and efficiently so we
haven't seen the issues you are.

I'm thinking I should just scrap the LogFile (tail) collector and write it
from scratch in pure .NET

Thanks for all the feedback.

**Comment by pmcevoy** [comment]
One of our chaps found this - may be of use:  http://www.codeproject.com/Articles/7568/Tail-NET

So I'm interested to hear more about your usage of ELK+Timber, because UDP as an Shipper input doesn't grok with me:  why would your app write to the network so that a local Timber instance can ship centrally?  Do you have a central Timber instance?

We are following the pattern detailed here: https://ianunruh.com/2014/05/monitor-everything-part-2.html  with Timber acting as a Shipper on each of our app servers.  If our apps were to write logs using UDP, then we'd just get the Indexer (a logstash instance) to pick them up and avoid having a shipper altogether.  I understood that the whole point of a shipper was to be local to the app?  

OK - I realize that this is an OSS project and I'm not contributing to the solution.  Please don't take my comments as complaints - I appreciate all the work that OSS guys do, even if my company doesn't...

**Comment by efontana** [comment]
All good comments, the real reason that we use UDP/TCP locally and use TimberWinR is because of the filtering capabilities.   The messages are tagged with things like "datacenter=(name)" and other fields are mutated for consistency as well as filters for loglevel.  Each datacenter has a local cluster, which then forwards to a central cluster, there are 8 datacenters.    We have all this in production on 1000s of servers and are not having these issues, probably because we aren't tailing many many log files.  They all are shipping WindowsEvent logs as well as well as IIS logs.  So TimberWinR gets you millions of log messages every day via UDP/TCP as well as hundreds of thousands of IIS and WindowsEvent logs, thats why we use it.

**Comment by efontana** [comment]
I'm going to give it a shot to re-write the Tail code to be native and not use LogParser.  I'm sure I can make it more efficient.

**Comment by efontana** [comment]
I'm writing a new input type "TailFiles" which will use the new code, preserving the Logs code, I hope to have a stab at an early version today if your willing to try it out.

**Comment by efontana** [comment]
I just added the TailFiles listener which is compatable with the same style input as Logs.  It's building now.  The snip you want is this:

It uses a Native implementation, I tested it with LogRolling and it seems fine.  It uses the persistence database located in C:\Logs.timberwinrdb  to detect last position and/or new file detection.

{
    "TimberWinR": {
        "Inputs": {
            "TailFiles": [
                {
                    "location": "C:\Logs1\*.log",
                    "recurse": -1  
                }
            ]
        }
    }
}

**Comment by efontana** [comment]
The new build will be here:

https://ci.appveyor.com/project/efontana/timberwinr-147/build/1.2.349

And pushed to Chocolatey when done.
